apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: freecan-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec: 
  tls: 
  - hosts: 
    - outspeedfunding.com
    - www.outspeedfunding.com
    secretName: tls-secret
  rules:
  - host: outspeedfunding.com
    http: &http_rules
      paths:
      - path: /
        backend:
          service:
            name: freecan-app-service
            port: 
              number: 3000  
        pathType: Prefix
      - path: /api
        backend: 
          service: 
            name: freecan-app-service-backend
            port:
              number: 3000
        pathType: Prefix
  - host: www.outspeedfunding.com
    http: *http_rules
