apiVersion: v1
kind: Service
metadata: 
  name: freecan-app-service
  labels:
    app: freecan-app
spec: 
  ports:
  - port: 3000
  selector:
    app: freecan-app
    tier: web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata: 
  name: freecan-app-service-backend
  labels:
    app: freecan-app
spec: 
  ports:
  - port: 3000
  selector:
    app: freecan-app
    tier: web
  type: ClusterIP